# Generated by Django 3.1 on 2020-08-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_iswarning'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=50, null=True, unique=True)),
                ('employee_id', models.CharField(max_length=100, null=True)),
                ('last_location_str', models.CharField(blank=True, max_length=100, null=True)),
                ('last_connect_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('node_name', models.CharField(max_length=5, unique=True)),
                ('is_car_exist', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='isWarning',
        ),
        migrations.DeleteModel(
            name='SensorCriteria',
        ),
        migrations.RemoveField(
            model_name='sensorvalue',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Hat',
        ),
        migrations.DeleteModel(
            name='SensorValue',
        ),
    ]
