# Generated by Django 3.1 on 2020-08-12 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200812_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charger',
            name='employee_id',
        ),
    ]
